image: openjdk:8-jdk

stages:
- setup
- test
- build
- publish
- release

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches
  - build/*
  - projects/*

setup:
  stage: setup
  script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - chmod +x gradlew && ./gradlew setup
  except:
    - tags

test:
  stage: test
  script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd projects && ../gradlew Magma:test
  except:
    - tags

build:
  stage: build
  script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - chmod +x gradlew && ./gradlew outputJar
  artifacts:
    paths:
      - build/distributions/*server.*
  except:
    - tags

publish:
  stage: publish
  script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - chmod +x gradlew && ./gradlew publish
  only:
  - master
  except:
    - tags

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - release-cli --server-url https://git.magmafoundation.org --job-token=$CI_JOB_TOKEN create --name "Release $CI_COMMIT_SHORT_SHA" --description "Magma Release" --tag-name "$CI_COMMIT_SHORT_SHA" --ref "$CI_COMMIT_SHORT_SHA" --assets-link "{\"url\":\"https://git.magmafoundation.org/api/v4/projects/7/packages/maven/magmafoundation/Magma/1.12.2-$CI_COMMIT_SHORT_SHA/Magma-1.12.2-$CI_COMMIT_SHORT_SHA.jar\",\"name\":\"Magma-1.12.2-$CI_COMMIT_SHORT_SHA.jar\"}"
  only:
  - master
  except:
    - tags

after_script:
- echo "End CI"
